import Providers from "@/app/components/Providers";
import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import Header from "./components/Header/Header";
import "./styles/globals.scss";
import "@splidejs/react-splide/css";
import Footer from "./components/Footer/Footer";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const interSans = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`${montserrat.variable} ${interSans.variable}`}
        suppressHydrationWarning
      >
        <Header />
        <Providers>{children}</Providers>
        <Footer />
      </body>
    </html>
  );
}
